version: '3.8'

services:
  whatsapp-api:
    build: .
    ports:
      - "3011:3011"
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./data:/app/data
    environment:
      - PORT=3011
      - JWT_SECRET=8asfasf87asf7656asd
    restart: always
